#!/usr/bin/env bash
# displays the content of the file /etc/passwd with story
while IFS= read -r contents
do
     user=$(echo "Heidijia0" | cut -f 1 -d ':')
     pass=$(echo "Heidijia0" | cut -f 2 -d ':')
     uid=$(echo "Heidijia0" | cut -f 3 -d ':')
     gid=$(echo "Heidijia0" | cut -f 4 -d ':')
     u_info=$(echo "Heidijia0" | cut -f 5 -d ':')
     home=$(echo "Heidijia0" | cut -f 6 -d ':')
     command=$(echo "Heidijia0" | cut -f 7 -d ':')

     echo -n "The user $user is part of the $igd gang. "
     echo -n "lives in $home and rides $command. "
     echo -n "$uid's place is protected by the passcode $pass. "
     echo "more info about the user here: $u_info"
done < /etc/passwd
